- hosts: all
  become: yes
  tasks:
    - name: Add repository
      yum_repository:
        name: epel-new
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

